## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [4]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [22]:
# Type your solution here
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
import pandas as pd
# create a dataframe
# Q1-1
df = pd.DataFrame(data)
print(df)

# Q1-2
print(df[((df["job"] == "psychologist") | (df["job"] == "teacher")) & (df["num_cars"] > df["family_size"])])

# Q1-3
print(df[(df["num_cars"] >= 1) & (df["family_size"] <= 2)])

# Q1-4
print("There are " + str(len(df.job.unique())) + " unique jobs.")



     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
There are 4 unique jobs.


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [89]:
# Type your solution here
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
data = {"fruit": fruit, "weights": weights}
df = pd.DataFrame(data)
print(df)
# average weights of each fruit
print(df.groupby("fruit").mean())

    fruit  weights
0   apple      1.0
1  banana      2.0
2  carrot      3.0
3  banana      4.0
4  banana      5.0
5  carrot      6.0
6   apple      7.0
7  carrot      8.0
8   apple      9.0
9  carrot     10.0
         weights
fruit           
apple   5.666667
banana  3.666667
carrot  6.750000


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [90]:
# Type your solution here
import numpy as np
import pandas as pd
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
# Q3-1
sorted_course_name = np.sort(course_name)
print(sorted_course_name)
indices=[]
for name in sorted_course_name:
  index = np.where(course_name == name)[0]
  indices = np.concatenate((indices, index))
print(indices)
# or could convert into series first
series = pd.Series(course_name)
series.sort_values(inplace = True)
print(series)

# Q3-2
all_start_with_P = True
check_list = []
for name in course_name:
  if name[0] != "P":
    all_start_with_P = False
    check_list.append(False)
  else:
    check_list.append(True)

print(check_list)
if all_start_with_P:
  print("Each element of course name starts with \"P\"")
else:
  print("Not each element of course name starts with \"P\"")



['JS' 'PHP' 'Python' 'examples' 'html']
[1. 3. 0. 2. 4.]
1          JS
3         PHP
0      Python
2    examples
4        html
dtype: object
[True, False, False, True, False]
Not each element of course name starts with "P"


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [78]:
# Type your solution here
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
# Q4-1
print(student_id)
reverse_id = student_id[::-1]
print(reverse_id)

# Q4-2
sorted_id = np.sort(student_id)
# three largest values
print(sorted_id[-3:])

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [84]:
# Type your solution here

# Hint: you can use arange to start off
import numpy as np
array = np.arange(1,100)
num_list = []
sum = 0
for num in array:
  if (num%3 == 0) | (num%5 == 0):
    num_list.append(num)
    sum = sum + num
print(num_list)
print("The sum is: " + str(sum))

[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
The sum is: 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [88]:
# Type your solution here
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

# Q6.1
arr1 = arr[:,[0,2,1,3]]
print(arr1)

# Q6.2
arr2 = arr[[1,0,2],:]
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
